on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

permissions:
  contents: write

name: Release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          #files: |
          #  dist/**
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          #body: "Changelog of release ${{ github.ref_name }}."
          #append_body: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
